# Data Analysis

In [11]:
# Imports
import matplotlib as plt
import pandas as pd
import numpy as np
from scipy import stats as st


jurd_df = pd.read_csv("data/Warehouse_and_Retail_Sales.csv")
retail_sales_array = jurd_df['RETAIL SALES'].to_numpy()
print(retail_sales_array)

warehouse_sales_array = jurd_df['WAREHOUSE SALES'].to_numpy()
print(warehouse_sales_array)

total_sales_array = retail_sales_array + warehouse_sales_array
print(total_sales_array)

to_drop = ['ITEM CODE', 'RETAIL TRANSFERS']
jurd_df = jurd_df.drop(columns = to_drop)

[0. 0. 0. ... 0. 0. 0.]
[  0.   0.   0. ...  32. -35. -81.]
[  0.   0.   0. ...  32. -35. -81.]


<h1 style="color: cornflowerblue;">Basic Analysis: Summary Stats</h1>

<h2 style="color: cornflowerblue;">Mean</h2>

In [15]:
# Mean Retail Sales
avg_retail_sales = np.mean(retail_sales_array)
avg_retail_sales = np.round(avg_retail_sales, decimals=2)
print(f'Average Retail Cases Sold: {avg_retail_sales} cases')
# Mean Warehouse Sales
avg_warehouse_sales = np.mean(warehouse_sales_array)
avg_warehouse_sales = np.round(avg_warehouse_sales,decimals=2)
print(f'Average Warehouse Cases Sold: {avg_warehouse_sales} cases')
# Mean Total Sales
avg_total_sales = np.mean(total_sales_array)
avg_total_sales = np.round(avg_total_sales,decimals=2)
print(f'Average Total Cases Sold: {avg_total_sales} cases')

Average Retail Cases Sold: 6.56 cases
Average Warehouse Cases Sold: 22.62 cases
Average Total Cases Sold: 29.19 cases


<h2 style="color: cornflowerblue;">Median</h2>

In [19]:
# Median Retail Sales
median_retail_sales = np.median(retail_sales_array)
np_arr = jurd_df['RETAIL SALES'].to_numpy()
sorted_idxs = np.argsort(retail_sales_array)
med_idx = sorted_idxs[round(len(sorted_idxs)/2)]
median_retail_sales = np.round(retail_sales_array, decimals=2)
print(f'Median Retail Cases Sold: {np_arr[med_idx]} cases')
# Median Warehouse Sales
median_warehouse_sales = np.median(warehouse_sales_array)
np_arr = jurd_df['WAREHOUSE SALES'].to_numpy()
sorted_idxs = np.argsort(warehouse_sales_array)
med_idx = sorted_idxs[round(len(sorted_idxs)/2)]
median_warehouse_sales = np.round(warehouse_sales_array, decimals=2)
print(f'Median Warehouse Cases Sold: {np_arr[med_idx]} cases')
# Median Total Sales
median_total_sales = np.median(total_sales_array)
np_arr = total_sales_array
sorted_idxs = np.argsort(total_sales_array)
med_idx = sorted_idxs[round(len(sorted_idxs)/2)]
median_total_sales = np.round(total_sales_array, decimals=2)
print(f'Median Total Cases Sold: {np_arr[med_idx]} cases')

Median Retail Cases Sold: 0.33 cases
Median Warehouse Cases Sold: 1.0 cases
Median Total Cases Sold: 2.01 cases


<h2 style="color: cornflowerblue;">a la Mode</h2>

In [20]:
# Mode Retail Sales
mode_retail_sales = st.mode(retail_sales_array)
print(f'Mode Retail Cases Sold: {mode_retail_sales.mode}')
# Mode Warehouse Sales
mode_warehouse_sales = st.mode(warehouse_sales_array)
print(f'Mode Warehouse Cases Sold: {mode_warehouse_sales.mode}')
# Mode Total Sales
mode_total_sales = st.mode(total_sales_array)
print(f'Mode Total Cases Sold: {mode_total_sales.mode}')

Mode Retail Cases Sold: 0.0
Mode Warehouse Cases Sold: 0.0
Mode Total Cases Sold: 1.0


<h2 style="color: cornflowerblue;">Range</h2>

In [21]:
# Retail Range Calculations
retail_sales_max = np.max(retail_sales_array) # Find Max value
retail_sales_min = np.min(retail_sales_array) # Find Min value
range_retail_sales = retail_sales_max - retail_sales_min
print(f'Range of Retail Cases Sold: {range_retail_sales}')
# Warehouse Range Calculations
warehouse_sales_max = np.max(warehouse_sales_array) # Find Max value
warehouse_sales_min = np.min(warehouse_sales_array) # Find Min value
range_warehouse_sales = warehouse_sales_max - warehouse_sales_min
print(f'Range of Warehouse Cases Sold: {range_warehouse_sales}')
# Total Range Calculations
total_sales_max = np.max(total_sales_array) # Find Max value
total_sales_min = np.min(total_sales_array) # Find Min value
range_total_sales = total_sales_max - total_sales_min
print(f'Range of Total Cases Sold: {range_total_sales}')

Range of Retail Cases Sold: 1623.09
Range of Warehouse Cases Sold: 21267.75
Range of Total Cases Sold: 22221.75


<h2 style="color: cornflowerblue;">Standard Deviation</h2>

In [22]:
# Std of Retail
std_retail_sales = np.std(retail_sales_array)
rnd_std_retail_sales = np.round(std_retail_sales, decimals=2)
print(f'Standard Deviation of Retail Cases Sold: {rnd_std_retail_sales} cases')
# Std of Warehouse
std_warehouse_sales = np.std(warehouse_sales_array)
rnd_std_warehouse_sales = np.round(std_warehouse_sales, decimals=2)
print(f'Standard Deviation of Warehouse Cases Sold: {rnd_std_warehouse_sales} cases')
# Std of Total
std_total_sales = np.std(total_sales_array)
rnd_std_total_sales = np.round(std_total_sales, decimals=2)
print(f'Standard Deviation of Total Cases Sold: {rnd_std_total_sales} cases')

Standard Deviation of Retail Cases Sold: 28.92 cases
Standard Deviation of Warehouse Cases Sold: 239.69 cases
Standard Deviation of Total Cases Sold: 254.29 cases


<h2 style="color: cornflowerblue;">Correlation Coefficient</h2>

In [23]:
coefficient = np.corrcoef(retail_sales_array, warehouse_sales_array)
print(f'The correlation coefficient is {coefficient[0,1]:.2f}, therefore there is a low correlation between Retail and Warehouse Sales')

The correlation coefficient is 0.46, therefore there is a low correlation between Retail and Warehouse Sales
